setxkbmap -option caps:escape
alias cctags='ctags -R --languages=ruby --exclude=.git --exclude=log . $(bundle list --paths)'
if { [ -n "$TMUX" ]; } then
  export TERM=screen-256color
else
  export TERM=xterm-256color
fi
alias ve='source ~/virtual_env/bin/activate'
alias tml="tmux list-sessions"
alias tma="tmux -2 attach -t $1"
alias tmk="tmux kill-session -t $1"

export EDITOR="nvim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export FZF_DEFAULT_COMMAND='ag -g ""'
#export FZF_DEFAULT_OPTS='--black'

export PATH=$PATH:$HOME/dotfiles/bin
export PATH=node_modules/.bin:$PATH

# VI-mode
bindkey -v
# 10ms for key sequences
KEYTIMEOUT=1

function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
bindkey -v '^?' backward-delete-char
