- name: apt-get update
  become: yes
  apt:
    update_cache: yes

- name: Make sure .zshrc_custom file exists
  file:
    path: ~/.zshrc_custom
    state: file

- name: Symlink zshrc to .zshrc file
  file:
    src: ~/development-environment/dotfiles/zshrc
    dest: ~/.zshrc
    state: link

- name: Install zsh
  become: yes
  apt:
    name: zsh
    state: present

- name: Set default shell to zsh
  shell: printf "{{ password }}\n" | chsh -s /usr/bin/zsh

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: Install zsh-syntax-highlighting plugin
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  args:
    creates: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Install zsh-autosuggestions plugin
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  args:
    creates: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
