- name: Add unstable nvim repo
  become: yes
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present

- name: apt-get update
  become: yes
  apt:
    update_cache: yes

- name: Install Neovim
  become: yes
  apt:
    name: neovim
    state: present

- name: Make sure .config directory exists
  file:
    path: ~/.config
    state: directory

- name: Symlink vimrc to init.vim file
  file:
    src: ~/development-environment/dotfiles/vim/vimrc
    dest: ~/development-environment/dotfiles/vim/init.vim
    state: link

- name: Symlink vim folder under ~/.config
  file:
    src: ~/development-environment/dotfiles/vim
    dest: ~/.config/nvim
    state: link

- name: Symlink vim folder under ~/.vim
  file:
    src: ~/development-environment/dotfiles/vim
    dest: ~/.vim
    state: link

- name: Create virtualenv for neovim2
  shell: |
    pyenv virtualenv 2.7.17 neovim2
  args:
    creates: ~/.pyenv/versions/neovim2

- name: Create virtualenv for neovim3
  shell: |
    pyenv virtualenv 3.6.6 neovim3
  args:
    creates: ~/.pyenv/versions/neovim3

- name: Install neovim2 environment pynvim and neovim packages
  shell: |
    pyenv activate neovim2
    pip install pynvim neovim

- name: Install neovim3 environment pynvim and neovim packages
  shell: |
    pyenv activate neovim3
    pip install pynvim neovim
