- name: Install pyenv
  shell: curl https://pyenv.run | bash
  args:
    creates: ~/.pyenv

- name: Install python 3.10.4
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv install 3.10.4
  args:
    creates: ~/.pyenv/versions/3.10.4

- name: Install python 2.7.18
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv install 2.7.18
  args:
    creates: ~/.pyenv/versions/2.7.18
