- name: Install pyenv
  shell: curl https://pyenv.run | bash
  args:
    creates: ~/.pyenv

- name: Install python 3.6.6
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv install 3.6.6
  args:
    creates: ~/.pyenv/versions/3.6.6

- name: Install python 2.7.11
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv install 2.7.11
  args:
    creates: ~/.pyenv/versions/2.7.11
