let g:python_host_prog = expand('~/.pyenv/versions/neovim2/bin/python')
let g:python3_host_prog = expand('~/.pyenv/versions/neovim3/bin/python')
let g:node_host_prog = expand('~/.nvm/versions/node/v16.15.0/bin/neovim-node-host')

syntax enable
filetype plugin indent on

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin'

Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'sainnhe/gruvbox-material'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'rust-lang/rust.vim'

call plug#end()

if has('termguicolors')
  set termguicolors
endif
set background=dark
let g:gruvbox_material_background = 'hard'
let g:gruvbox_material_visual = 'reverse'
colorscheme gruvbox-material

" Map leader key to space
noremap <Space> <NOP>
let mapleader = " "

map <S-k> <Nop>

" NERDTree
map <Leader>e :NERDTreeToggle<CR>

" Gitgutter
let g:gitgutter_realtime = 0
let g:gitgutter_eager = 0

" CTRL+Arrows to resize splits
nnoremap <C-left> :vertical resize -5<cr>
nnoremap <C-down> :resize +5<cr>
nnoremap <C-up> :resize -5<cr>
nnoremap <C-right> :vertical resize +5<cr>

" Typos
command QW wq
command Qw wq
command W w
command Q q
command Qa qa
nnoremap K <NOP>

" Undo & history & swp files
set undofile
set undodir=~/.vim/undodir//
set history=1000
set backupdir=~/.vim/backupdir//
set directory=~/.vim/swapfiles//

" Show column 80
set colorcolumn=80

" CTRL+C to Close buffer
nnoremap <C-c> :bp\|bd #<CR>

" FZF shortcuts
nnoremap <C-p> :Files<CR>
nmap <Leader>b :Buffers<CR>
nmap <Leader>s :GFiles?<CR>
nmap <Leader>c :Commits<CR>
nmap <Leader>r :History:<CR>
nmap gs :Gstatus<CR>
nmap gc :Gcommit<CR>

" Linenumbers
set relativenumber
set number

" Encodings
set encoding=utf-8
set fileencoding=utf-8

" Timeouts
set timeoutlen=1000
set ttimeoutlen=0

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Matching bracket
set showmatch

" Error Sounds
set noerrorbells
set novisualbell

" Scroll
set scrolloff=8
set sidescrolloff=15
set lazyredraw

" Wildmenu
set wildmode=longest,list,full
set wildmenu

" Highlight trailing spaces etc
set list listchars=tab:>-,trail:~,extends:>,precedes:<,nbsp:+
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Tabs vs spaces
set ts=2
set shiftwidth=2
set expandtab
set nostartofline

" Search for word under cursor
nnoremap <silent> <Leader>ag :Ag <C-R><C-W><CR>

" if hidden is not set, TextEdit might fail.
set hidden

" Better display for messages
set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

" Status bar
function! GitBranch()
  return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction

function! StatuslineGit()
  let l:branchname = GitBranch()
  return strlen(l:branchname) > 0?'  '.l:branchname.' ':''
endfunction

set statusline=
set statusline+=%R                              " readonly flag
set statusline+=%M                              " modified [+] flag
set statusline+=%#Cursor#                       " colour
set statusline+=%#CursorLine#                   " colour
set statusline+=\ %f\                           " relative file name
set statusline+=%{StatuslineGit()}              " git branch
set statusline+=%=                              " right align
set statusline+=%#CursorLine#                   " colour
set statusline+=\ %y\                           " file type
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
" Status bar end

"###### COC.nvim #######

"Extensions being used
"CocInstall coc-eslint coc-explorer coc-json coc-marketplace coc-prettier coc-tsserver coc-vetur

" Trigger autcomplete
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
inoremap <silent><expr> <C-x><C-z> coc#pum#visible() ? coc#pum#stop() : "\<C-x>\<C-z>"
" remap for complete to use tab and <cr>
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
inoremap <silent><expr> <c-space> coc#refresh()

hi CocSearch ctermfg=12 guifg=#18A3FF
hi CocMenuSel ctermbg=109 guibg=#13354A

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Use `:Format` to format current buffer
command! -nargs=0 Format :call CocAction('format')

" use `:OR` for organize import of current buffer
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
" Disable tmux navigator when zooming the Vim pane
let g:tmux_navigator_disable_when_zoomed = 1

" Prettier
command! -nargs=0 Prettier :CocCommand prettier.formatFile

lua <<EOF
require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all"
  ensure_installed = "all",

  -- Install parsers synchronously (only applied to `ensure_installed`)
  -- sync_install = false,

  -- List of parsers to ignore installing (for "all")
  -- ignore_install = { "javascript" },

  highlight = {
    -- `false` will disable the whole extension
    enable = true,

    -- NOTE: these are the names of the parsers and not the filetype. (for example if you want to
    -- disable highlighting for the `tex` filetype, you need to include `latex` in this list as this is
    -- the name of the parser)
    -- list of language that will be disabled
    -- disable = { "c", "rust" },

    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    -- additional_vim_regex_highlighting = false,
  },
}
EOF

let g:rustfmt_autosave = 1
