#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" -R --languages=ruby --exclude=.git --exclude=log --exclude=tmp --exclude=public --exclude=app/assets . $(bundle list --paths)
mv "$dir/$$.tags" "$dir/tags"
