- name: Download fzf
  shell: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  args:
    creates: ~/.fzf

- name: Install fzf
  shell: ~/.fzf/install --all
  args:
    creates: ~/.fzf/bin/fzf
